# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# for codecov
r_packages:
  - covr

# Fix build error package v8
addons:
  apt:
    packages:
      - libv8-dev

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
